from __future__ import annotations

from nalr.schemas.models import AgentSpec


def build_agent_registry() -> dict[str, AgentSpec]:
    specs = [
        AgentSpec(
            name="BodyStateAgent",
            class_kind="explicit",
            wakeup_rule="every_round_or_body_change",
            owned_skills=["update_body_state", "compute_body_bias", "apply_body_veto"],
            budget_class="L",
            fallback_policy="return_neutral",
        ),
        AgentSpec(
            name="RelationshipAgent",
            class_kind="explicit",
            wakeup_rule="target_or_relation_update_or_social_risk",
            owned_skills=["score_closeness", "compute_boundary_gate", "update_relation_trace"],
            budget_class="M",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="DesireAgent",
            class_kind="explicit",
            wakeup_rule="comfort_or_reward_cue_present",
            owned_skills=["score_immediate_reward", "compute_effort_avoidance", "suggest_low_cost_action"],
            budget_class="L",
            fallback_policy="return_neutral",
        ),
        AgentSpec(
            name="EmotionAgent",
            class_kind="explicit",
            wakeup_rule="affect_load_change_or_trigger",
            owned_skills=["update_affect_state", "compute_affect_bias", "trigger_affect_veto"],
            budget_class="M",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="DMNAgent",
            class_kind="explicit",
            wakeup_rule="idle_or_low_stimulus_or_rumination",
            owned_skills=["sample_dmn_intrusion", "score_rumination_pull", "select_spontaneous_topic"],
            budget_class="L",
            fallback_policy="return_neutral",
        ),
        AgentSpec(
            name="PFCAgent",
            class_kind="explicit",
            wakeup_rule="task_or_explanation_or_execution",
            owned_skills=["generate_candidates", "estimate_plan_depth", "bind_working_memory"],
            budget_class="H",
            fallback_policy="fallback_to_rules",
        ),
        AgentSpec(
            name="UnconsciousAgent",
            class_kind="implicit",
            wakeup_rule="boot_or_slow_variable_update",
            owned_skills=["load_temperament", "compute_trait_bias", "apply_chronic_shift"],
            budget_class="L",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="HippocampusAgent",
            class_kind="implicit",
            wakeup_rule="retrieval_writeback_or_forgetting_tick",
            owned_skills=[
                "encode_episode",
                "retrieve_by_cue",
                "apply_cue_weighted_decay",
                "compute_memory_interference",
                "fallback_to_gist_when_trace_weak",
            ],
            budget_class="M",
            fallback_policy="fallback_to_gist",
        ),
        AgentSpec(
            name="ThalamusAttentionAgent",
            class_kind="explicit",
            wakeup_rule="every_round_before_sampling",
            owned_skills=["aggregate_proposals", "normalize_distribution", "sample_action"],
            budget_class="M",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="SalienceAgent",
            class_kind="explicit",
            wakeup_rule="new_input_or_risk_or_conflict",
            owned_skills=["score_salience", "switch_mode", "interrupt_current_focus", "promote_event_to_workspace"],
            budget_class="M",
            fallback_policy="retry_once_then_degrade",
        ),
        AgentSpec(
            name="HabitAgent",
            class_kind="explicit",
            wakeup_rule="high_frequency_context_or_default_action_available",
            owned_skills=["compute_feedback_decay", "update_habit_strength", "suggest_default_action", "estimate_override_cost"],
            budget_class="L",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="ValueAgent",
            class_kind="explicit",
            wakeup_rule="after_candidates_generated",
            owned_skills=["estimate_subjective_value", "discount_delayed_reward", "price_social_cost", "score_uncertainty_penalty"],
            budget_class="M",
            fallback_policy="fallback_to_rules",
        ),
        AgentSpec(
            name="ConflictMonitorAgent",
            class_kind="explicit",
            wakeup_rule="after_proposal_aggregation",
            owned_skills=["score_conflict", "trigger_control_escalation", "request_resample", "mark_post_error_adjustment"],
            budget_class="M",
            fallback_policy="retry_once_then_degrade",
        ),
        AgentSpec(
            name="ResourceAgent",
            class_kind="implicit",
            wakeup_rule="budget_change_or_mode_switch",
            owned_skills=["compute_scarcity_index", "map_budget_to_bias", "suggest_resource_mode"],
            budget_class="L",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="CerebellarPredictor",
            class_kind="implicit",
            wakeup_rule="before_output_or_timing_correction",
            owned_skills=["predict_next_state", "compute_prediction_error", "smooth_response_timing", "micro_adjust_action"],
            budget_class="L",
            fallback_policy="return_neutral",
        ),
        AgentSpec(
            name="PerspectiveModel",
            class_kind="implicit",
            wakeup_rule="social_risk_or_misunderstanding_risk",
            owned_skills=["infer_other_state", "simulate_other_reaction", "estimate_misunderstanding_risk", "adjust_social_interpretation"],
            budget_class="H",
            fallback_policy="fallback_to_rules",
        ),
        AgentSpec(
            name="BehaviorPlausibilityGuard",
            class_kind="guard",
            wakeup_rule="after_sampling_before_output",
            owned_skills=["check_behavior_plausibility", "request_second_sampling", "escalate_value_reestimate"],
            budget_class="L",
            fallback_policy="fallback_to_rules",
        ),
        AgentSpec(
            name="ForcedModeSwitch",
            class_kind="guard",
            wakeup_rule="mode_lock_or_long_stall",
            owned_skills=["detect_mode_lock", "trigger_forced_focus_switch"],
            budget_class="L",
            fallback_policy="fallback_to_prior",
        ),
        AgentSpec(
            name="OutputGate",
            class_kind="guard",
            wakeup_rule="before_rendering",
            owned_skills=["apply_output_gate", "render_tone_profile", "compute_delay_profile"],
            budget_class="H",
            fallback_policy="fallback_to_rules",
        ),
    ]
    return {spec.name: spec for spec in specs}
