from __future__ import annotations

from nalr.schemas.models import (
    CircuitBreakerPolicy,
    FallbackRoute,
    SkillPermissionProfile,
    SkillSpec,
)
from nalr.skills.contracts import resolve_contract, serialize_contract


def _resolve_schema(contract):
    if isinstance(contract, dict):
        return {key: _resolve_schema(value) for key, value in contract.items()}
    return resolve_contract(contract)


def _skill(
    name: str,
    owner_module: str,
    input_schema,
    output_schema,
    timeout_ms: int,
    cost_class: str,
    failure_policy: str,
    trace_tags: list[str],
    *,
    skill_kind: str,
    sync_mode: str = "sync",
    policy_check: bool = False,
    idempotent: bool = True,
    output_kind: str = "scalar",
    permission: SkillPermissionProfile | None = None,
    fallback_route: FallbackRoute | None = None,
    breaker_policy: CircuitBreakerPolicy | None = None,
) -> SkillSpec:
    return SkillSpec(
        name=name,
        owner_module=owner_module,
        input_schema=_resolve_schema(input_schema),
        output_schema=_resolve_schema(output_schema),
        timeout_ms=timeout_ms,
        cost_class=cost_class,
        failure_policy=failure_policy,
        trace_tags=trace_tags,
        skill_kind=skill_kind,
        sync_mode=sync_mode,
        policy_check=policy_check,
        idempotent=idempotent,
        output_kind=output_kind,
        permission=permission or SkillPermissionProfile(),
        fallback_route=fallback_route,
        breaker_policy=breaker_policy,
    )


def _model_permission(*, social_risk: bool = False) -> SkillPermissionProfile:
    return SkillPermissionProfile(external_io=True, social_risk=social_risk)


def _model_fallback(name: str) -> FallbackRoute:
    return FallbackRoute(strategy="fallback_to_rules", target=name, cost_class="L")


def build_skill_registry() -> dict[str, SkillSpec]:
    specs = [
        _skill("update_body_state", "BodyStateAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_patch": "dict[str, Any]"}, 20, "L", "return_neutral", ["body", "state"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_body_bias", "BodyStateAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 20, "L", "return_neutral", ["proposal", "body"], skill_kind="proposing", output_kind="contribution"),
        _skill("apply_body_veto", "BodyStateAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"veto": "bool", "gated_actions": "list[str]"}, 10, "L", "return_neutral", ["body", "gate"], skill_kind="guarding", output_kind="veto"),
        _skill("score_closeness", "RelationshipAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"score": "float"}, 40, "M", "fallback_to_prior", ["relationship"], skill_kind="scoring"),
        _skill("compute_boundary_gate", "RelationshipAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"gate": "dict[str, float]", "boundary_level": "float"}, 35, "M", "fallback_to_prior", ["relationship", "gate"], skill_kind="guarding", policy_check=True, output_kind="gate"),
        _skill("update_relation_trace", "RelationshipAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_delta": "dict[str, Any]"}, 30, "M", "fallback_to_prior", ["relationship", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("score_immediate_reward", "DesireAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"score": "float"}, 20, "L", "return_neutral", ["desire"], skill_kind="scoring"),
        _skill("compute_effort_avoidance", "DesireAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 20, "L", "return_neutral", ["desire", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("suggest_low_cost_action", "DesireAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"action_hint": "str"}, 25, "L", "return_neutral", ["desire"], skill_kind="proposing", output_kind="action_hint"),
        _skill("update_affect_state", "EmotionAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_patch": "dict[str, Any]"}, 45, "M", "fallback_to_prior", ["emotion", "state"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_affect_bias", "EmotionAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 35, "M", "fallback_to_prior", ["emotion", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("trigger_affect_veto", "EmotionAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"veto": "bool"}, 20, "M", "fallback_to_prior", ["emotion", "gate"], skill_kind="guarding", output_kind="veto"),
        _skill("sample_dmn_intrusion", "DMNAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 25, "L", "return_neutral", ["dmn", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("score_rumination_pull", "DMNAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"score": "float"}, 20, "L", "return_neutral", ["dmn"], skill_kind="scoring"),
        _skill("select_spontaneous_topic", "DMNAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"topic_hint": "str"}, 25, "L", "return_neutral", ["dmn"], skill_kind="proposing", output_kind="action_hint"),
        _skill("generate_candidates", "PFCAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 60000, "H", "fallback_to_rules", ["proposal", "pfc"], skill_kind="planning", output_kind="contribution", policy_check=True, permission=_model_permission(), fallback_route=_model_fallback("PFCAgent.build_direct_action_contribution"), breaker_policy=CircuitBreakerPolicy(failure_threshold=3, cooldown_rounds=5)),
        _skill("estimate_plan_depth", "PFCAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"plan_depth": "int"}, 50, "M", "fallback_to_rules", ["pfc"], skill_kind="planning", output_kind="plan_depth"),
        _skill("bind_working_memory", "PFCAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"wm_update": "dict[str, Any]"}, 20, "L", "fallback_to_rules", ["pfc", "memory"], skill_kind="planning", output_kind="state_patch"),
        _skill("score_salience", "SalienceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 50, "M", "retry_once_then_degrade", ["salience", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("switch_mode", "SalienceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"mode_flag": "str"}, 20, "L", "retry_once_then_degrade", ["salience", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("interrupt_current_focus", "SalienceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"interrupt": "bool"}, 15, "L", "retry_once_then_degrade", ["salience"], skill_kind="guarding", output_kind="flag"),
        _skill("promote_event_to_workspace", "SalienceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"workspace_delta": "dict[str, Any]"}, 20, "L", "retry_once_then_degrade", ["salience", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_feedback_decay", "HabitAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 20, "L", "fallback_to_prior", ["habit"], skill_kind="scoring"),
        _skill("update_habit_strength", "HabitAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_update": "dict[str, Any]"}, 30, "L", "fallback_to_prior", ["habit", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("suggest_default_action", "HabitAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 25, "L", "fallback_to_prior", ["habit", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("estimate_override_cost", "HabitAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"cost": "float"}, 20, "L", "fallback_to_prior", ["habit"], skill_kind="scoring"),
        _skill("estimate_subjective_value", "ValueAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scores": "dict[str, float]"}, 60, "M", "fallback_to_rules", ["value"], skill_kind="scoring", output_kind="score_map"),
        _skill("discount_delayed_reward", "ValueAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 25, "L", "fallback_to_rules", ["value"], skill_kind="scoring"),
        _skill("price_social_cost", "ValueAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 25, "L", "fallback_to_rules", ["value", "relationship"], skill_kind="scoring", policy_check=True),
        _skill("score_uncertainty_penalty", "ValueAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"penalty": "float"}, 20, "L", "fallback_to_rules", ["value"], skill_kind="scoring"),
        _skill(
            "score_conflict",
            "ConflictMonitorAgent",
            {"signals": "list[ActionEvidenceSignal]", "probability_field": "dict[str, Any]"},
            {
                "score": "float",
                "total_score": "float",
                "components": "dict[str, float]",
                "priority_signals": "dict[str, float]",
                "dominant_conflicts": "list[str]",
                "critical_conflict": "bool",
            },
            45,
            "M",
            "retry_once_then_degrade",
            ["conflict", "proposal"],
            skill_kind="scoring",
        ),
        _skill(
            "trigger_control_escalation",
            "ConflictMonitorAgent",
            {
                "assessment": "dict[str, Any]",
                "probability_field": "dict[str, Any]",
                "conflict_arbitration": "dict[str, Any]",
                "attempts": "int",
                "hot_active": "bool",
            },
            {
                "flag": "bool",
                "winning_priority": "optional[str]",
                "blocked_actions": "list[str]",
                "action_scales": "dict[str, float]",
                "applied_template": "optional[str]",
                "reason": "str",
                "post_error_adjustment": "dict[str, Any]",
                "repair_transition": "dict[str, Any]",
                "repair_state_snapshot": "dict[str, Any]",
                "repair_ledger_tail": "list[dict[str, Any]]",
            },
            15,
            "L",
            "retry_once_then_degrade",
            ["conflict"],
            skill_kind="guarding",
            output_kind="flag",
        ),
        _skill(
            "request_resample",
            "ConflictMonitorAgent",
            {"assessment": "dict[str, Any]", "attempts": "int"},
            {"flag": "bool", "allowed_resamples": "int", "force_compromise": "bool", "critical_conflict": "bool"},
            10,
            "L",
            "retry_once_then_degrade",
            ["conflict", "sampling"],
            skill_kind="guarding",
            output_kind="flag",
        ),
        _skill(
            "mark_post_error_adjustment",
            "ConflictMonitorAgent",
            {
                "state": "RuntimeState",
                "round_id": "int",
                "resolution": "dict[str, Any]",
                "compromise": "dict[str, Any]",
                "deadlock_fuse_triggered": "bool",
                "top_action_before": "optional[str]",
                "top_action_after": "optional[str]",
                "blocked_actions": "list[str]",
                "safe_mode_before": "bool",
            },
            {
                "repair_mode": "optional[str]",
                "post_error_adjustment": "dict[str, Any]",
                "repair_transition": "dict[str, Any]",
                "repair_state_snapshot": "dict[str, Any]",
                "repair_ledger_append": "dict[str, Any]",
                "conflict_safe_mode_owner": "optional[str]",
                "safe_mode_patch": "bool",
                "repair_cooldown_rounds_patch": "int",
            },
            15,
            "L",
            "retry_once_then_degrade",
            ["conflict", "repair"],
            skill_kind="guarding",
            output_kind="flag",
        ),
        _skill("check_behavior_plausibility", "BehaviorPlausibilityGuard", {"action": "str", "scenario": "str", "relation_state": "dict[str, Any]"}, {"pass": "bool", "plausibility_fail_score": "float"}, 25, "L", "retry_once_then_degrade", ["guard", "plausibility"], skill_kind="guarding", output_kind="gate"),
        _skill("encode_episode", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"writeback": "dict[str, Any]"}, 60, "M", "fallback_to_gist", ["memory", "writeback"], skill_kind="recall", output_kind="memory_op"),
        _skill("retrieve_by_cue", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"recall_set": "list[dict[str, Any]]"}, 120, "M", "fallback_to_gist", ["memory", "recall"], skill_kind="recall", output_kind="recall_set"),
        _skill("apply_cue_weighted_decay", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 30, "L", "fallback_to_gist", ["memory"], skill_kind="ops"),
        _skill("compute_memory_interference", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 30, "L", "fallback_to_gist", ["memory"], skill_kind="scoring"),
        _skill("fallback_to_gist_when_trace_weak", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"gist": "dict[str, Any]"}, 30, "L", "fallback_to_gist", ["memory", "recall"], skill_kind="recall", output_kind="gist"),
        _skill("compute_scarcity_index", "ResourceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"scalar": "float"}, 20, "L", "fallback_to_prior", ["proposal", "resource"], skill_kind="scoring"),
        _skill("map_budget_to_bias", "ResourceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 20, "L", "fallback_to_prior", ["resource", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("suggest_resource_mode", "ResourceAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"mode_flag": "str"}, 15, "L", "fallback_to_prior", ["resource", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("predict_next_state", "CerebellarPredictor", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_prediction": "dict[str, Any]"}, 20, "L", "return_neutral", ["timing"], skill_kind="scoring", output_kind="state_prediction"),
        _skill("compute_prediction_error", "CerebellarPredictor", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"error": "float"}, 20, "L", "return_neutral", ["timing"], skill_kind="scoring"),
        _skill("smooth_response_timing", "CerebellarPredictor", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"timing_delta": "dict[str, Any]"}, 15, "L", "return_neutral", ["timing", "render"], skill_kind="rendering", output_kind="timing_profile"),
        _skill("micro_adjust_action", "CerebellarPredictor", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 15, "L", "return_neutral", ["timing", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("infer_other_state", "PerspectiveModel", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]", "sampled_action": "str", "relation_state": "dict[str, Any]"}, {"state_hypothesis": "dict[str, Any]"}, 60000, "H", "fallback_to_rules", ["perspective", "social"], skill_kind="recall", policy_check=True, output_kind="state_hypothesis", permission=_model_permission(social_risk=True), fallback_route=_model_fallback("PerspectiveModel.fallback_infer_other_state"), breaker_policy=CircuitBreakerPolicy()),
        _skill("simulate_other_reaction", "PerspectiveModel", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]", "sampled_action": "str", "relation_state": "dict[str, Any]"}, {"reaction_hypothesis": "dict[str, Any]"}, 60000, "H", "fallback_to_rules", ["perspective", "social"], skill_kind="recall", policy_check=True, output_kind="reaction_hypothesis", permission=_model_permission(social_risk=True), fallback_route=_model_fallback("PerspectiveModel.fallback_simulate_other_reaction"), breaker_policy=CircuitBreakerPolicy()),
        _skill("estimate_misunderstanding_risk", "PerspectiveModel", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"risk": "float"}, 60, "M", "fallback_to_rules", ["perspective", "social"], skill_kind="scoring", policy_check=True),
        _skill("adjust_social_interpretation", "PerspectiveModel", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 50, "M", "fallback_to_rules", ["perspective", "social"], skill_kind="proposing", policy_check=True, output_kind="contribution"),
        _skill("score_query_intent", "IntentProbabilityLayer", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "relation_state": "dict[str, Any]", "slow_variables": "dict[str, Any]"}, "QueryIntentState", 25, "L", "fallback_to_prior", ["intent", "query"], skill_kind="scoring", output_kind="intent_state"),
        _skill("score_disclosure_intent", "IntentProbabilityLayer", {"query_state": "QueryIntentState", "state": "RuntimeState", "scenario": "dict[str, Any]", "relation_state": "dict[str, Any]", "slow_variables": "dict[str, Any]"}, "DisclosureIntentState", 25, "L", "fallback_to_prior", ["intent", "disclosure"], skill_kind="scoring", output_kind="intent_state"),
        _skill("consume_quantum_entropy", "QuantumEntropyPool", {"byte_count": "int", "purpose": "str"}, "QuantumEntropyRef", 80, "M", "fallback_to_prior", ["entropy", "sampling"], skill_kind="ops", output_kind="entropy_ref"),
        _skill("request_second_sampling", "BehaviorPlausibilityGuard", {"fail_score": "float", "attempts": "int"}, {"flag": "bool"}, 10, "L", "fallback_to_rules", ["guard", "sampling"], skill_kind="guarding", output_kind="flag"),
        _skill("escalate_value_reestimate", "BehaviorPlausibilityGuard", {"fail_score": "float"}, {"flag": "bool"}, 10, "L", "fallback_to_rules", ["guard", "value"], skill_kind="guarding", output_kind="flag"),
        _skill("detect_mode_lock", "ForcedModeSwitch", {"history": "list[str]", "focus_lock_count": "int"}, {"lock_score": "float"}, 20, "L", "fallback_to_prior", ["guard", "mode"], skill_kind="scoring"),
        _skill("trigger_forced_focus_switch", "ForcedModeSwitch", {"lock_score": "float"}, {"switch_flag": "bool"}, 10, "L", "fallback_to_prior", ["guard", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("apply_output_gate", "OutputGate", {"action": "str", "state": "RuntimeState", "scenario": "str", "relation_state": "dict[str, Any]"}, {"gate": "float"}, 20, "L", "fallback_to_rules", ["render", "gate"], skill_kind="guarding", policy_check=True, output_kind="gate"),
        _skill("render_tone_profile", "OutputGate", {"expression_profile": "ExpressionProfile"}, {"tone_params": "dict[str, float]"}, 40, "M", "fallback_to_rules", ["render"], skill_kind="rendering", output_kind="tone_profile"),
        _skill("compute_delay_profile", "OutputGate", {"expression_profile": "ExpressionProfile"}, {"delay_params": "dict[str, float]"}, 20, "L", "fallback_to_rules", ["render", "timing"], skill_kind="rendering", output_kind="delay_profile"),
        _skill("load_temperament", "UnconsciousAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"baseline": "dict[str, Any]"}, 20, "L", "fallback_to_prior", ["trait"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_trait_bias", "UnconsciousAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, "ProbabilisticContribution", 20, "L", "fallback_to_prior", ["trait", "proposal"], skill_kind="proposing", output_kind="contribution"),
        _skill("render_expression", "Renderer", {"render_plan": "RenderPlan"}, {"text": "str", "route": "str", "model": "str"}, 60000, "H", "fallback_to_rules", ["render", "expression"], skill_kind="rendering", output_kind="rendered_expression", policy_check=True, permission=_model_permission(), fallback_route=_model_fallback("renderer.fallback_render_text"), breaker_policy=CircuitBreakerPolicy()),
        _skill("apply_chronic_shift", "UnconsciousAgent", {"event": "RoundEvent", "state": "RuntimeState", "scenario": "dict[str, Any]", "context": "dict[str, Any]"}, {"state_patch": "dict[str, Any]"}, 20, "L", "fallback_to_prior", ["trait", "state"], skill_kind="ops", output_kind="state_patch"),
        _skill("heartbeat_check", "RuntimeController", {"state": "RuntimeState"}, {"health": "dict[str, Any]"}, 20, "L", "switch_safe_mode", ["ops", "health"], skill_kind="ops", output_kind="health"),
        _skill("checkpoint_create", "RuntimeController", {"state": "RuntimeState"}, {"checkpoint": "dict[str, Any]"}, 20, "L", "switch_safe_mode", ["ops", "checkpoint"], skill_kind="ops", sync_mode="async", output_kind="checkpoint"),
        _skill("rewind_state", "RuntimeController", {"checkpoint_id": "str"}, {"state": "dict[str, Any]"}, 40, "M", "switch_safe_mode", ["ops", "checkpoint"], skill_kind="ops", output_kind="state_patch"),
        _skill("switch_to_safe_mode", "RuntimeController", {"state": "RuntimeState"}, {"state_patch": "dict[str, Any]"}, 20, "L", "switch_safe_mode", ["ops", "mode"], skill_kind="ops", output_kind="state_patch"),
        _skill("record_round_trace", "proposal_trace", {"trace": "RoundTrace"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack", permission=SkillPermissionProfile(scope="trace_append")),
        _skill("record_agent_contribution", "proposal_trace", {"trace": "dict[str, Any]"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack", permission=SkillPermissionProfile(scope="trace_append")),
        _skill("flush_trace_batch", "proposal_trace", {"batch": "list[dict[str, Any]]"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack", permission=SkillPermissionProfile(scope="trace_append")),
    ]
    return {spec.name: spec for spec in specs}


__all__ = ["build_skill_registry", "serialize_contract"]
