from __future__ import annotations

from nalr.schemas.models import SkillSpec


def _skill(
    name: str,
    owner_module: str,
    input_schema: dict[str, str],
    output_schema: dict[str, str],
    timeout_ms: int,
    cost_class: str,
    failure_policy: str,
    trace_tags: list[str],
    *,
    skill_kind: str,
    sync_mode: str = "sync",
    policy_check: bool = False,
    idempotent: bool = True,
    output_kind: str = "scalar",
) -> SkillSpec:
    return SkillSpec(
        name=name,
        owner_module=owner_module,
        input_schema=input_schema,
        output_schema=output_schema,
        timeout_ms=timeout_ms,
        cost_class=cost_class,
        failure_policy=failure_policy,
        trace_tags=trace_tags,
        skill_kind=skill_kind,
        sync_mode=sync_mode,
        policy_check=policy_check,
        idempotent=idempotent,
        output_kind=output_kind,
    )


def build_skill_registry() -> dict[str, SkillSpec]:
    specs = [
        _skill("update_body_state", "BodyStateAgent", {"state": "RuntimeState", "event": "RoundEvent"}, {"state_patch": "dict"}, 20, "L", "return_neutral", ["body", "state"], skill_kind="proposing", output_kind="state_patch"),
        _skill("compute_body_bias", "BodyStateAgent", {"body_energy": "float", "event": "RoundEvent"}, {"action_preferences": "dict[str, float]"}, 20, "L", "return_neutral", ["proposal", "body"], skill_kind="proposing", output_kind="proposal"),
        _skill("apply_body_veto", "BodyStateAgent", {"body_energy": "float", "candidates": "list[str]"}, {"veto": "bool"}, 10, "L", "return_neutral", ["body", "gate"], skill_kind="guarding", output_kind="veto"),
        _skill("score_closeness", "RelationshipAgent", {"target": "str", "memory": "dict"}, {"score": "float"}, 40, "M", "fallback_to_prior", ["relationship"], skill_kind="scoring"),
        _skill("compute_boundary_gate", "RelationshipAgent", {"target": "str", "context": "dict"}, {"gate": "dict"}, 35, "M", "fallback_to_prior", ["relationship", "gate"], skill_kind="guarding", policy_check=True, output_kind="gate"),
        _skill("update_relation_trace", "RelationshipAgent", {"target": "str", "event": "RoundEvent"}, {"state_delta": "dict"}, 30, "M", "fallback_to_prior", ["relationship", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("score_immediate_reward", "DesireAgent", {"event": "RoundEvent", "state": "RuntimeState"}, {"score": "float"}, 20, "L", "return_neutral", ["desire"], skill_kind="scoring"),
        _skill("compute_effort_avoidance", "DesireAgent", {"state": "RuntimeState", "candidates": "list[str]"}, {"action_preferences": "dict[str, float]"}, 20, "L", "return_neutral", ["desire", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("suggest_low_cost_action", "DesireAgent", {"candidates": "list[str]"}, {"action_hint": "str"}, 25, "L", "return_neutral", ["desire"], skill_kind="proposing", output_kind="action_hint"),
        _skill("update_affect_state", "EmotionAgent", {"state": "RuntimeState", "event": "RoundEvent"}, {"state_patch": "dict"}, 45, "M", "fallback_to_prior", ["emotion", "state"], skill_kind="proposing", output_kind="state_patch"),
        _skill("compute_affect_bias", "EmotionAgent", {"mood": "float", "event": "RoundEvent"}, {"action_preferences": "dict[str, float]"}, 35, "M", "fallback_to_prior", ["emotion", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("trigger_affect_veto", "EmotionAgent", {"mood": "float", "event": "RoundEvent"}, {"veto": "bool"}, 20, "M", "fallback_to_prior", ["emotion", "gate"], skill_kind="guarding", output_kind="veto"),
        _skill("sample_dmn_intrusion", "DMNAgent", {"state": "RuntimeState", "scenario": "str"}, {"action_preferences": "dict[str, float]"}, 25, "L", "return_neutral", ["dmn", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("score_rumination_pull", "DMNAgent", {"unfinished_topics": "list[str]"}, {"score": "float"}, 20, "L", "return_neutral", ["dmn"], skill_kind="scoring"),
        _skill("select_spontaneous_topic", "DMNAgent", {"memory": "dict"}, {"topic_hint": "str"}, 25, "L", "return_neutral", ["dmn"], skill_kind="proposing", output_kind="topic_hint"),
        _skill("generate_candidates", "PFCAgent", {"scenario": "str", "event": "RoundEvent"}, {"action_preferences": "dict[str, float]"}, 300, "H", "fallback_to_rules", ["proposal", "pfc"], skill_kind="planning", output_kind="candidate_actions"),
        _skill("estimate_plan_depth", "PFCAgent", {"scenario": "str", "event": "RoundEvent"}, {"plan_depth": "int"}, 50, "M", "fallback_to_rules", ["pfc"], skill_kind="planning", output_kind="plan_depth"),
        _skill("bind_working_memory", "PFCAgent", {"workspace": "dict", "event": "RoundEvent"}, {"wm_update": "dict"}, 20, "L", "fallback_to_rules", ["pfc", "memory"], skill_kind="planning", output_kind="state_patch"),
        _skill("score_salience", "SalienceAgent", {"event": "RoundEvent", "state": "RuntimeState"}, {"score": "float"}, 50, "M", "retry_once_then_degrade", ["salience", "proposal"], skill_kind="scoring"),
        _skill("switch_mode", "SalienceAgent", {"score": "float", "mode": "str"}, {"mode_flag": "str"}, 20, "L", "retry_once_then_degrade", ["salience", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("interrupt_current_focus", "SalienceAgent", {"score": "float", "focus": "str"}, {"interrupt": "bool"}, 15, "L", "retry_once_then_degrade", ["salience"], skill_kind="guarding", output_kind="flag"),
        _skill("promote_event_to_workspace", "SalienceAgent", {"event": "RoundEvent", "workspace": "dict"}, {"workspace_delta": "dict"}, 20, "L", "retry_once_then_degrade", ["salience", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_feedback_decay", "HabitAgent", {"history": "list[dict]"}, {"scalar": "float"}, 20, "L", "fallback_to_prior", ["habit"], skill_kind="scoring"),
        _skill("update_habit_strength", "HabitAgent", {"cue": "str", "history": "list[dict]"}, {"state_update": "dict"}, 30, "L", "fallback_to_prior", ["habit", "memory"], skill_kind="ops", output_kind="state_patch"),
        _skill("suggest_default_action", "HabitAgent", {"cue": "str", "context": "dict"}, {"action_preferences": "dict[str, float]"}, 25, "L", "fallback_to_prior", ["habit", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("estimate_override_cost", "HabitAgent", {"cue": "str", "context": "dict"}, {"cost": "float"}, 20, "L", "fallback_to_prior", ["habit"], skill_kind="scoring"),
        _skill("estimate_subjective_value", "ValueAgent", {"candidates": "list[str]", "context": "dict"}, {"scores": "dict[str, float]"}, 60, "M", "fallback_to_rules", ["value", "proposal"], skill_kind="scoring", output_kind="score_map"),
        _skill("discount_delayed_reward", "ValueAgent", {"candidates": "list[str]"}, {"scalar": "float"}, 25, "L", "fallback_to_rules", ["value"], skill_kind="scoring"),
        _skill("price_social_cost", "ValueAgent", {"candidates": "list[str]", "target": "str"}, {"scalar": "float"}, 25, "L", "fallback_to_rules", ["value", "relationship"], skill_kind="scoring", policy_check=True),
        _skill("score_uncertainty_penalty", "ValueAgent", {"candidates": "list[str]", "context": "dict"}, {"penalty": "float"}, 20, "L", "fallback_to_rules", ["value"], skill_kind="scoring"),
        _skill("score_conflict", "ConflictMonitorAgent", {"proposals": "list[ProposalBundle]"}, {"score": "float"}, 45, "M", "retry_once_then_degrade", ["conflict", "proposal"], skill_kind="scoring"),
        _skill("trigger_control_escalation", "ConflictMonitorAgent", {"score": "float"}, {"flag": "bool"}, 15, "L", "retry_once_then_degrade", ["conflict"], skill_kind="guarding", output_kind="flag"),
        _skill("request_resample", "ConflictMonitorAgent", {"score": "float", "attempts": "int"}, {"flag": "bool"}, 10, "L", "retry_once_then_degrade", ["conflict", "sampling"], skill_kind="guarding", output_kind="flag"),
        _skill("check_behavior_plausibility", "BehaviorPlausibilityGuard", {"action": "str", "context": "dict"}, {"pass": "bool"}, 25, "L", "retry_once_then_degrade", ["guard", "plausibility"], skill_kind="guarding", output_kind="gate"),
        _skill("encode_episode", "HippocampusAgent", {"event": "RoundEvent", "state": "RuntimeState"}, {"writeback": "dict"}, 60, "M", "fallback_to_gist", ["memory", "writeback"], skill_kind="recall", output_kind="memory_op"),
        _skill("retrieve_by_cue", "HippocampusAgent", {"cue": "str", "mode": "str"}, {"recall_set": "list[dict]"}, 120, "M", "fallback_to_gist", ["memory", "recall"], skill_kind="recall", output_kind="recall_set"),
        _skill("apply_cue_weighted_decay", "HippocampusAgent", {"cue": "str", "store": "dict"}, {"scalar": "float"}, 30, "L", "fallback_to_gist", ["memory"], skill_kind="ops"),
        _skill("compute_memory_interference", "HippocampusAgent", {"cue": "str", "store": "dict"}, {"scalar": "float"}, 30, "L", "fallback_to_gist", ["memory"], skill_kind="scoring"),
        _skill("fallback_to_gist_when_trace_weak", "HippocampusAgent", {"cue": "str", "store": "dict"}, {"gist": "dict"}, 30, "L", "fallback_to_gist", ["memory", "recall"], skill_kind="recall", output_kind="gist"),
        _skill("compute_scarcity_index", "ResourceAgent", {"budget_remaining": "float"}, {"action_preferences": "dict[str, float]"}, 20, "L", "fallback_to_prior", ["proposal", "resource"], skill_kind="scoring", output_kind="proposal"),
        _skill("map_budget_to_bias", "ResourceAgent", {"budget_remaining": "float", "mode": "str"}, {"action_preferences": "dict[str, float]"}, 20, "L", "fallback_to_prior", ["resource", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("suggest_resource_mode", "ResourceAgent", {"budget_remaining": "float", "mode": "str"}, {"mode_flag": "str"}, 15, "L", "fallback_to_prior", ["resource", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("predict_next_state", "CerebellarPredictor", {"history": "list[dict]"}, {"state_prediction": "dict"}, 20, "L", "return_neutral", ["timing"], skill_kind="scoring", output_kind="state_prediction"),
        _skill("compute_prediction_error", "CerebellarPredictor", {"history": "list[dict]", "action": "str"}, {"error": "float"}, 20, "L", "return_neutral", ["timing"], skill_kind="scoring"),
        _skill("smooth_response_timing", "CerebellarPredictor", {"state": "RuntimeState", "style": "dict"}, {"timing_delta": "dict"}, 15, "L", "return_neutral", ["timing", "render"], skill_kind="rendering", output_kind="timing_profile"),
        _skill("micro_adjust_action", "CerebellarPredictor", {"action": "str", "style": "dict"}, {"tiny_bias": "dict"}, 15, "L", "return_neutral", ["timing", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("infer_other_state", "PerspectiveModel", {"target": "str", "dialogue": "dict"}, {"state_hypothesis": "dict"}, 120, "H", "fallback_to_rules", ["perspective", "social"], skill_kind="recall", policy_check=True, output_kind="state_hypothesis"),
        _skill("simulate_other_reaction", "PerspectiveModel", {"target": "str", "action": "str"}, {"reaction_hypothesis": "dict"}, 150, "H", "fallback_to_rules", ["perspective", "social"], skill_kind="recall", policy_check=True, output_kind="reaction_hypothesis"),
        _skill("estimate_misunderstanding_risk", "PerspectiveModel", {"target": "str", "dialogue": "dict"}, {"risk": "float"}, 60, "M", "fallback_to_rules", ["perspective", "social"], skill_kind="scoring", policy_check=True),
        _skill("adjust_social_interpretation", "PerspectiveModel", {"target": "str", "dialogue": "dict"}, {"interpretation_delta": "dict"}, 50, "M", "fallback_to_rules", ["perspective", "social"], skill_kind="proposing", policy_check=True, output_kind="proposal"),
        _skill("aggregate_proposals", "ThalamusAttentionAgent", {"proposals": "list[ProposalBundle]"}, {"distribution": "dict[str, float]"}, 40, "M", "fallback_to_prior", ["sampling"], skill_kind="scoring", output_kind="distribution"),
        _skill("normalize_distribution", "ThalamusAttentionAgent", {"distribution": "dict[str, float]"}, {"distribution": "dict[str, float]"}, 20, "L", "fallback_to_prior", ["sampling"], skill_kind="scoring", output_kind="distribution"),
        _skill("sample_action", "ThalamusAttentionAgent", {"distribution": "dict[str, float]", "seed_ref": "int"}, {"action": "ActionCandidate"}, 10, "L", "fallback_to_prior", ["sampling"], skill_kind="proposing", output_kind="sampled_action"),
        _skill("request_second_sampling", "BehaviorPlausibilityGuard", {"action": "str", "context": "dict"}, {"flag": "bool"}, 10, "L", "fallback_to_rules", ["guard", "sampling"], skill_kind="guarding", output_kind="flag"),
        _skill("escalate_value_reestimate", "BehaviorPlausibilityGuard", {"action": "str", "context": "dict"}, {"flag": "bool"}, 10, "L", "fallback_to_rules", ["guard", "value"], skill_kind="guarding", output_kind="flag"),
        _skill("detect_mode_lock", "ForcedModeSwitch", {"history": "list[str]"}, {"lock_score": "float"}, 20, "L", "fallback_to_prior", ["guard", "mode"], skill_kind="scoring"),
        _skill("trigger_forced_focus_switch", "ForcedModeSwitch", {"lock_score": "float"}, {"switch_flag": "bool"}, 10, "L", "fallback_to_prior", ["guard", "mode"], skill_kind="guarding", output_kind="mode_switch"),
        _skill("apply_output_gate", "OutputGate", {"action": "str", "context": "dict"}, {"gated_action": "dict"}, 20, "L", "fallback_to_rules", ["render", "gate"], skill_kind="guarding", policy_check=True, output_kind="gate"),
        _skill("render_tone_profile", "OutputGate", {"action": "str", "state": "RuntimeState", "scenario": "str"}, {"tone_params": "dict"}, 40, "M", "fallback_to_rules", ["render"], skill_kind="rendering", output_kind="tone_profile"),
        _skill("compute_delay_profile", "OutputGate", {"action": "str", "state": "RuntimeState"}, {"delay_params": "dict"}, 20, "L", "fallback_to_rules", ["render", "timing"], skill_kind="rendering", output_kind="delay_profile"),
        _skill("load_temperament", "UnconsciousAgent", {"temperament": "dict"}, {"baseline": "dict"}, 20, "L", "fallback_to_prior", ["trait"], skill_kind="ops", output_kind="state_patch"),
        _skill("compute_trait_bias", "UnconsciousAgent", {"temperament": "dict", "state": "RuntimeState"}, {"bias": "dict[str, float]"}, 20, "L", "fallback_to_prior", ["trait", "proposal"], skill_kind="proposing", output_kind="proposal"),
        _skill("apply_chronic_shift", "UnconsciousAgent", {"temperament": "dict", "state": "RuntimeState"}, {"state_patch": "dict"}, 20, "L", "fallback_to_prior", ["trait", "state"], skill_kind="ops", output_kind="state_patch"),
        _skill("heartbeat_check", "RuntimeController", {"state": "RuntimeState"}, {"health": "dict"}, 20, "L", "switch_safe_mode", ["ops", "health"], skill_kind="ops", output_kind="health"),
        _skill("checkpoint_create", "RuntimeController", {"state": "RuntimeState"}, {"checkpoint": "dict"}, 20, "L", "switch_safe_mode", ["ops", "checkpoint"], skill_kind="ops", sync_mode="async", output_kind="checkpoint"),
        _skill("rewind_state", "RuntimeController", {"checkpoint_id": "str"}, {"state": "dict"}, 40, "M", "switch_safe_mode", ["ops", "checkpoint"], skill_kind="ops", output_kind="state_patch"),
        _skill("switch_to_safe_mode", "RuntimeController", {"state": "RuntimeState"}, {"state_patch": "dict"}, 20, "L", "switch_safe_mode", ["ops", "mode"], skill_kind="ops", output_kind="state_patch"),
        _skill("record_round_trace", "proposal_trace", {"trace": "RoundTrace"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack"),
        _skill("record_agent_contribution", "proposal_trace", {"trace": "dict"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack"),
        _skill("flush_trace_batch", "proposal_trace", {"batch": "list[dict]"}, {"ack": "bool"}, 10, "L", "return_neutral", ["trace"], skill_kind="ops", sync_mode="async", output_kind="ack"),
    ]
    return {spec.name: spec for spec in specs}
